services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oddava-app
    env_file:
      - .env
    expose:
      - "4321"
    networks:
      anishows_proxy:
        aliases:
          - oddava-app
    restart: unless-stopped

networks:
  anishows_proxy:
    external: true
    name: anishows_default
